# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(921, 523)
        self.btn_open = QtWidgets.QPushButton(Dialog)
        self.btn_open.setGeometry(QtCore.QRect(300, 470, 81, 26))
        self.btn_open.setObjectName("btn_open")
        self.btn_submit = QtWidgets.QPushButton(Dialog)
        self.btn_submit.setGeometry(QtCore.QRect(530, 470, 81, 26))
        self.btn_submit.setObjectName("btn_submit")
        self.original_image = QtWidgets.QLabel(Dialog)
        self.original_image.setGeometry(QtCore.QRect(80, 70, 358, 358))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setKerning(True)
        self.original_image.setFont(font)
        self.original_image.setStyleSheet("border:1px solid rgb(0,0,0)")
        self.original_image.setObjectName("original_image")
        self.cartoon_image = QtWidgets.QLabel(Dialog)
        self.cartoon_image.setGeometry(QtCore.QRect(500, 70, 358, 358))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cartoon_image.setFont(font)
        self.cartoon_image.setStyleSheet("border:1px solid rgb(0,0,0)")
        self.cartoon_image.setObjectName("cartoon_image")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_open.setText(_translate("Dialog", "选择图片"))
        self.btn_submit.setText(_translate("Dialog", "转换"))
        self.original_image.setText(_translate("Dialog", "                                   原始图片"))
        self.cartoon_image.setText(_translate("Dialog", "                                    动漫图像"))
